=== ZachariaszStrus/Uczelnia/PT/Java/proj4/src/proj4/catalog.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">
    
    <xs:element name="productCatalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="product" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="product">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="price"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="name" type="xs:string"/>
    
    <xs:simpleType name="restDec">
        <xs:restriction base="xs:decimal">
           <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="price">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="restDec">
                    <xs:attribute name="currency" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== ZachariaszStrus/Uczelnia/PT/Java/proj4/src/proj4/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>

<productCatalog xmlns="http://www.w3schools.com"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.w3schools.com catalog.xsd">
    <product>
        <name>TDK DVD-R 1-8x 4.7GB (10xDVD Cake BOX)</name>
        <price currency="PLN">15</price>
    </product>
    <product>
        <name>Verbatim DVD-R DualLayer 8.5GB</name>
        <price currency="PLN">12</price>
    </product>
    <product>
        <name>Verbatim (100xCD) Cake BOX</name>
        <price currency="PLN">99</price>
    </product>
    <product>
        <name>Kingston CompactFlash 4GB</name>
        <price currency="EUR">7</price>
    </product>
    <product>
        <name>Kingston DataTraveler 100 G2 8GB</name>
        <price currency="EUR">6</price>
    </product>
</productCatalog>
